//! **Regular expressions and choice lists → GBNF**, so one verified matcher (`grammar`) serves every
//! constraint: vLLM's `guided_regex` / `structured_outputs.regex` and `guided_choice`.
//!
//! The meaning of a regex constraint is Python's `re.fullmatch(pattern, output, re.ASCII)` — the whole
//! output must match, as outlines and vLLM define it — and that is what the tests check against
//! (tests/fixtures/grammar/regex_fullmatch.json, generated by Python's `re`). Supported: literals and escapes,
//! `.` (any character but newline, as `re` without DOTALL), classes `[...]` / `[^...]` with ranges, the
//! shorthands `\d \w \s \D \W \S` in their ASCII meaning, groups `( )` and `(?: )`, alternation, and the
//! quantifiers `* + ? {m} {m,} {m,n}` (lazy forms too — laziness does not change what fully matches). Anchors
//! `^`/`$` at the ends are accepted and are no-ops under full-match semantics. Refused by name, never
//! approximated: backreferences, lookaround, named-group references, inline flags, anchors elsewhere.

/// A GBNF char-class body for one code point (escaped for use inside `[...]`).
fn class_char(c: char) -> String {
    match c {
        '\\' | ']' | '[' | '-' | '^' | '"' => format!("\\{c}"),
        '\n' => "\\n".into(), '\t' => "\\t".into(), '\r' => "\\r".into(),
        c if (c as u32) < 0x20 || c as u32 == 0x7f => format!("\\x{:02X}", c as u32),
        c => c.to_string(),
    }
}

/// A GBNF string literal for `s`.
pub fn literal(s: &str) -> String {
    let mut o = String::from("\"");
    for c in s.chars() {
        match c {
            '"' => o.push_str("\\\""), '\\' => o.push_str("\\\\"), '\n' => o.push_str("\\n"), '\t' => o.push_str("\\t"),
            '\r' => o.push_str("\\r"),
            c if (c as u32) < 0x20 || c as u32 == 0x7f => o.push_str(&format!("\\x{:02X}", c as u32)),
            c => o.push(c),
        }
    }
    o.push('"');
    o
}

/// `root ::= "a" | "b" | …` — vLLM's `guided_choice`.
pub fn choice_to_gbnf(choices: &[String]) -> Result<String, String> {
    if choices.is_empty() { return Err("guided_choice needs at least one choice".into()); }
    Ok(format!("root ::= {}", choices.iter().map(|c| literal(c)).collect::<Vec<_>>().join(" | ")))
}

struct Rx<'a> { s: Vec<char>, p: usize, src: &'a str }

impl Rx<'_> {
    fn peek(&self) -> Option<char> { self.s.get(self.p).copied() }
    fn err(&self, what: &str) -> String { format!("regex {:?}: {what} at offset {}", self.src, self.p) }

    fn alternation(&mut self) -> Result<String, String> {
        let mut alts = vec![self.sequence()?];
        while self.peek() == Some('|') { self.p += 1; alts.push(self.sequence()?); }
        Ok(if alts.len() == 1 { alts.pop().unwrap() } else { format!("({})", alts.join(" | ")) })
    }

    fn sequence(&mut self) -> Result<String, String> {
        let mut items: Vec<String> = Vec::new();
        while let Some(c) = self.peek() {
            if c == '|' || c == ')' { break; }
            let atom = self.atom()?;
            let atom = self.quantifier(atom)?;
            items.push(atom);
        }
        // An empty alternative is the empty string.
        Ok(if items.is_empty() { "\"\"".to_string() } else { items.join(" ") })
    }

    fn quantifier(&mut self, atom: String) -> Result<String, String> {
        let q = match self.peek() {
            Some('*') => { self.p += 1; "*".to_string() }
            Some('+') => { self.p += 1; "+".to_string() }
            Some('?') => { self.p += 1; "?".to_string() }
            Some('{') => {
                let save = self.p;
                self.p += 1;
                let num = |r: &mut Self| { let st = r.p; while r.peek().is_some_and(|c| c.is_ascii_digit()) { r.p += 1; } r.s[st..r.p].iter().collect::<String>() };
                let a = num(self);
                if a.is_empty() { self.p = save; return Ok(atom); } // a literal '{' (Python treats a non-quantifier brace as text)
                let q = if self.peek() == Some(',') { self.p += 1; let b = num(self); format!("{{{a},{b}}}") } else { format!("{{{a}}}") };
                if self.peek() != Some('}') { self.p = save; return Ok(atom); }
                self.p += 1;
                q
            }
            _ => return Ok(atom),
        };
        // Lazy and possessive suffixes do not change which strings fully match.
        if matches!(self.peek(), Some('?') | Some('+')) && q.len() >= 1 {
            if self.peek() == Some('+') { return Err(self.err("possessive quantifiers are not supported")); }
            self.p += 1;
        }
        if matches!(self.peek(), Some('*' | '+' | '?')) { return Err(self.err("multiple repeat")); }
        Ok(format!("({atom}){q}"))
    }

    fn escape_class(c: char) -> Option<&'static str> {
        Some(match c {
            'd' => "[0-9]", 'D' => "[^0-9]", 'w' => "[a-zA-Z0-9_]", 'W' => "[^a-zA-Z0-9_]",
            's' => "[ \\t\\n\\r\\x0C\\x0B]", 'S' => "[^ \\t\\n\\r\\x0C\\x0B]",
            _ => return None,
        })
    }

    fn escaped_char(&mut self) -> Result<char, String> {
        let c = self.peek().ok_or_else(|| self.err("dangling backslash"))?;
        self.p += 1;
        Ok(match c {
            'n' => '\n', 't' => '\t', 'r' => '\r', 'f' => '\x0c', 'v' => '\x0b', '0' => '\0',
            'x' => {
                let h: String = self.s.get(self.p..self.p + 2).ok_or_else(|| self.err("bad \\x"))?.iter().collect();
                self.p += 2;
                char::from_u32(u32::from_str_radix(&h, 16).map_err(|_| self.err("bad \\x"))?).ok_or_else(|| self.err("bad \\x"))?
            }
            'u' => {
                let h: String = self.s.get(self.p..self.p + 4).ok_or_else(|| self.err("bad \\u"))?.iter().collect();
                self.p += 4;
                char::from_u32(u32::from_str_radix(&h, 16).map_err(|_| self.err("bad \\u"))?).ok_or_else(|| self.err("bad \\u"))?
            }
            c if c.is_ascii_digit() => return Err(self.err("backreferences are not supported")),
            'b' | 'B' | 'A' | 'Z' | 'z' | 'G' => return Err(self.err(&format!("the anchor \\{c} is not supported"))),
            c if c.is_ascii_alphanumeric() => return Err(self.err(&format!("unknown escape \\{c}"))),
            c => c,
        })
    }

    fn atom(&mut self) -> Result<String, String> {
        let c = self.peek().unwrap();
        self.p += 1;
        match c {
            '(' => {
                if self.peek() == Some('?') {
                    self.p += 1;
                    match self.peek() {
                        Some(':') => { self.p += 1; }
                        Some('P') if self.s.get(self.p + 1) == Some(&'<') => {
                            self.p += 2;
                            while self.peek().is_some_and(|c| c != '>') { self.p += 1; }
                            self.p += 1;
                        }
                        _ => return Err(self.err("lookaround, inline flags and group references are not supported")),
                    }
                }
                let inner = self.alternation()?;
                if self.peek() != Some(')') { return Err(self.err("missing )")); }
                self.p += 1;
                Ok(format!("({inner})"))
            }
            '[' => self.class(),
            '.' => Ok("[^\\n]".to_string()),
            '^' if self.p == 1 => Ok("\"\"".to_string()),
            '$' if self.p == self.s.len() => Ok("\"\"".to_string()),
            '^' | '$' => Err(self.err("anchors inside the pattern are not supported")),
            '\\' => {
                if let Some(k) = self.peek().and_then(Self::escape_class) { self.p += 1; return Ok(k.to_string()); }
                let ch = self.escaped_char()?;
                Ok(literal(&ch.to_string()))
            }
            '*' | '+' | '?' => Err(self.err("nothing to repeat")),
            c => Ok(literal(&c.to_string())),
        }
    }

    fn class(&mut self) -> Result<String, String> {
        let mut neg = false;
        if self.peek() == Some('^') { neg = true; self.p += 1; }
        let mut body = String::new();
        let mut first = true;
        loop {
            let c = self.peek().ok_or_else(|| self.err("unterminated character set"))?;
            if c == ']' && !first { self.p += 1; break; }
            first = false;
            self.p += 1;
            let lo = if c == '\\' {
                if let Some(k) = self.peek().and_then(Self::escape_class) {
                    // A shorthand inside a class: splice its members (negated shorthands cannot be spliced).
                    if k.starts_with("[^") { return Err(self.err("a negated shorthand inside a class is not supported")); }
                    self.p += 1;
                    body.push_str(&k[1..k.len() - 1]);
                    continue;
                }
                self.escaped_char()?
            } else { c };
            if self.peek() == Some('-') && self.s.get(self.p + 1).is_some_and(|&n| n != ']') {
                self.p += 1;
                let hc = self.peek().unwrap();
                self.p += 1;
                let hi = if hc == '\\' { self.escaped_char()? } else { hc };
                if hi < lo { return Err(self.err("bad character range")); }
                body.push_str(&format!("{}-{}", class_char(lo), class_char(hi)));
            } else {
                body.push_str(&class_char(lo));
            }
        }
        Ok(format!("[{}{body}]", if neg { "^" } else { "" }))
    }
}

/// A regex (Python `re` syntax, full-match, ASCII shorthands) as a GBNF grammar with start symbol `root`.
pub fn regex_to_gbnf(pattern: &str) -> Result<String, String> {
    let mut r = Rx { s: pattern.chars().collect(), p: 0, src: pattern };
    let body = r.alternation()?;
    if r.p != r.s.len() { return Err(r.err("unbalanced parenthesis")); }
    Ok(format!("root ::= {body}"))
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::grammar::{Grammar, Matcher};
    use std::sync::Arc;

    fn full(g: &Arc<Grammar>, s: &str) -> bool {
        let mut m = Matcher::new(g.clone());
        s.bytes().all(|b| m.step(b)) && m.can_stop()
    }

    /// Every (pattern, string) pair agrees with Python's `re.fullmatch(pattern, s, re.ASCII)`.
    #[test]
    fn regex_constraints_accept_exactly_what_python_fullmatch_accepts() {
        let fx: serde_json::Value = serde_json::from_str(include_str!("../tests/fixtures/grammar/regex_fullmatch.json")).unwrap();
        let mut n = 0;
        for c in fx["cases"].as_array().unwrap() {
            let pat = c["pattern"].as_str().unwrap();
            let src = regex_to_gbnf(pat).unwrap_or_else(|e| panic!("{e}"));
            let g = Arc::new(Grammar::parse(&src, "root", &|_| None).unwrap_or_else(|e| panic!("{pat} -> {src}: {e}")));
            for t in c["strings"].as_array().unwrap() {
                let (s, want) = (t[0].as_str().unwrap(), t[1].as_bool().unwrap());
                assert_eq!(full(&g, s), want, "pattern {pat:?} (gbnf {src:?}) on {s:?}: Python re.fullmatch says {want}");
                n += 1;
            }
        }
        assert!(n > 300, "only {n} checks — the fixture shrank");
        for bad in ["(a)\\1", "(?=a)b", "a{2}+", "a^b"] { assert!(regex_to_gbnf(bad).is_err(), "{bad} must be refused"); }
    }

    #[test]
    fn a_choice_matches_its_options_and_nothing_else() {
        let g = Arc::new(Grammar::parse(&choice_to_gbnf(&["yes".into(), "no".into(), "say \"hi\"".into()]).unwrap(), "root", &|_| None).unwrap());
        assert!(full(&g, "yes") && full(&g, "no") && full(&g, "say \"hi\""));
        assert!(!full(&g, "ye") && !full(&g, "yesno") && !full(&g, "No"));
    }
}
