#!/usr/bin/env python3
"""Generate `src/unicode_classes.rs` — \\p{L}, \\p{M}, \\p{N} — from llama.cpp's OWN table.

⛔ THE SOURCE IS THE ORACLE'S SOURCE, deliberately. Ferric's tokenizer is checked against
`llama-tokenize`, so the character classes have to be the ones llama.cpp uses, not merely "correct
Unicode". Deriving them from a different Unicode version, or from Rust's `char` methods, reintroduces
exactly the divergence this file exists to remove:

  Rust's `char::is_alphabetic()` is NOT `\\p{L}`. It is `\\p{L}` plus Other_Alphabetic, which INCLUDES
  many combining marks. Measured consequences before this table existed:
    - Thai U+0E31/U+0E35 are Mn, but `is_alphabetic()` says true -> Ferric ran letter runs THROUGH
      them where llama.cpp broke, so every qwen2 checkpoint missed `สวัสดีชาวโลก` (19/20).
    - Devanagari virama U+094D is Mn and `is_alphabetic()` says FALSE, while vowel sign U+0947 is Mn
      and says true -> a syllable split mid-word (`नमस्ते`).
  One predicate, wrong in BOTH directions, depending on the script.

    python3 gen_unicode_classes.py <llama.cpp/src/unicode-data.cpp> > ../src/unicode_classes.rs
"""
import re, sys

LETTER, MARK, NUMBER = 0x0004, 0x0010, 0x0002
src = open(sys.argv[1]).read()
body = src[src.index("unicode_ranges_flags"):]
body = body[:body.index("};")]
pairs = [(int(a, 16), int(b, 16)) for a, b in re.findall(r"\{(0x[0-9a-fA-F]+),\s*(0x[0-9a-fA-F]+)\}", body)]
# ⚠ Validate the PARSE STRUCTURALLY, not against a magic count. The first version asserted
# `> 6000` because that is how many `{0x` occurrences the whole FILE has — but the file holds several
# tables, and this one legitimately has 2273 entries. A count guessed from the wrong denominator
# fails a correct parse and would have sent me looking for a bug that was not there.
assert len(pairs) > 1000, f"only parsed {len(pairs)} entries — did the table move?"
assert all(pairs[k][0] < pairs[k + 1][0] for k in range(len(pairs) - 1)), "starts must be ascending"
assert pairs[-1][0] >= 0x110000, f"table stops at U+{pairs[-1][0]:04X}, not past the last codepoint"

def _flags(cp):
    lo, hi, best = 0, len(pairs) - 1, 0
    while lo <= hi:
        mid = (lo + hi) // 2
        if pairs[mid][0] <= cp: best, lo = pairs[mid][1], mid + 1
        else: hi = mid - 1
    return best
# the exact codepoints whose misclassification caused the shipped defects
for cp, mask, why in [(0x0E31, MARK, "Thai MAI HAN-AKAT: Mn, but Rust calls it alphabetic"),
                      (0x0E2A, LETTER, "Thai SO SUA: a real letter"),
                      (0x094D, MARK, "Devanagari virama: Mn, and Rust calls it NOT alphabetic"),
                      (0x0947, MARK, "Devanagari vowel sign E: Mn, and Rust calls it alphabetic"),
                      (0x0061, LETTER, "latin a"), (0x0035, NUMBER, "digit 5")]:
    assert _flags(cp) & mask, f"U+{cp:04X} misparsed ({why})"

def ranges(mask):
    out = []
    for i, (start, flags) in enumerate(pairs):
        if not (flags & mask):
            continue
        end = pairs[i + 1][0] - 1 if i + 1 < len(pairs) else 0x10FFFF
        if out and start == out[-1][1] + 1:
            out[-1][1] = end
        else:
            out.append([start, end])
    return out

L, M, N = ranges(LETTER), ranges(MARK), ranges(NUMBER)
print("// @generated by examples/gen_unicode_classes.py from llama.cpp's unicode-data.cpp —")
print("// the SAME table the reference tokenizer uses. Do not hand-edit; regenerate.")
print("//")
print("// Rust's char::is_alphabetic() is \\p{L} PLUS Other_Alphabetic, so it is wrong in BOTH")
print("// directions for a tokenizer: it swallows Thai/Arabic combining marks that \\p{L} excludes,")
print("// and it rejects the Devanagari virama that \\p{M} includes.")
for name, rs in (("LETTER", L), ("MARK", M), ("NUMBER", N)):
    print(f"\n/// `\\p{{{name[0]}}}` — {len(rs)} ranges, {sum(b - a + 1 for a, b in rs)} codepoints.")
    print(f"pub(crate) static {name}_RANGES: &[(u32, u32)] = &[")
    for i in range(0, len(rs), 6):
        print("    " + " ".join(f"({a:#08x},{b:#08x})," for a, b in rs[i:i + 6]))
    print("];")
print("""
#[inline]
fn in_ranges(c: char, rs: &[(u32, u32)]) -> bool {
    let c = c as u32;
    rs.binary_search_by(|&(lo, hi)| if hi < c { std::cmp::Ordering::Less }
                        else if lo > c { std::cmp::Ordering::Greater }
                        else { std::cmp::Ordering::Equal }).is_ok()
}

/// `\\p{L}` — Unicode category L*, exactly as the reference tokenizer sees it.
#[inline] pub fn is_letter(c: char) -> bool { in_ranges(c, LETTER_RANGES) }
/// `\\p{M}` — Unicode categories Mn, Mc, Me.
#[inline] pub fn is_mark(c: char) -> bool { in_ranges(c, MARK_RANGES) }
/// `\\p{N}` — Unicode category N*.
#[inline] pub fn is_number_cat(c: char) -> bool { in_ranges(c, NUMBER_RANGES) }""")
